name: parkinson
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

# dependencies:
#   flutter:
#     sdk: flutter
#   cupertino_icons: ^1.0.2
#   firebase_core: ^2.25.4
#   google_maps_flutter: ^2.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # provider: ^6.0.5
  cached_network_image: ^3.2.1
  flutter_svg: ^2.0.9
  flutter_rating_bar: ^4.0.1
  readmore: ^2.1.0
  intl: ^0.18.0
  # flutter_native_splash: ^2.3.1
  # firebase_core: 2.23.0
  # firebase_auth: 4.14.1
  # firebase_storage: 11.6.6
  # firebase_database: 10.4.6
  # cloud_firestore: 4.15.5
  image_picker: ^1.0.7
  http: ^1.2.1
  firebase_messaging: ^14.7.16
  flutter_local_notifications: ^16.3.2
  app_settings: ^5.1.1
  shared_preferences: ^2.2.2
  flutter_notification_channel: ^2.0.0
  cupertino_icons: ^1.0.6
  # flutter_image_compress: ^2.1.0
  path_provider: ^2.1.2
  photo_view: ^0.14.0
  location_geocoder: ^1.0.5
  lottie: ^3.1.0
  timezone: ^0.9.2
  flutter_tts: ^4.0.2
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  firebase_storage: ^11.7.4
  firebase_database: ^10.5.4
  cloud_firestore: ^4.17.2
  speech_to_text: ^6.6.1
  animated_text_kit: ^4.2.2
  alarm: ^3.1.2
  url_launcher:
  # text_to_speech: ^0.2.3

# flutter_native_splash:
#   color: "#33C0B3"
#   image: "assets/images/background.png"
#   web: false

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterBlackItalic.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
